version: "2"

services:
  balena-starter-interface:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NETWORK_MODE: bridge # Tell the app if running in `bridge` or `host` network mode
      SET_HOSTNAME: "balena" # Optional. Changes the device hostname. UI will become accesible on `balena.local`.
      UDEV: on # Enables ability to auto mount USB drives in to the container
    restart: always
    ports:
      - "80:80"
    volumes:
      - "bdi_db:/app/db" # Stores UI database files
      - "bdi_storage:/app/storage" # Storage for the File Manager. See docs for more info.
    privileged: true # This can be removed if not using the USB mounting feature

    # If using the File Manager to access volumes on other containers, ensure this container `depends_on` your
    # other container using the below:
    # depends_on:
    #  - "your-other-container-name"

    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  # Optional Wi-Fi controller:
  # https://github.com/balena-labs-research/python-wifi-connect
  python-wifi-connect:
    image: ghcr.io/balena-labs-research/python-wifi-connect:latest
    environment:
      # Listening IP and port
      PWC_HOST: bridge # `bridge` specifies that this is on the bridge network and to use container name
      PWC_PORT: 9090

      # Hotspot details
      PWC_HOTSPOT_SSID: "balena Starter Interface" # Name as it appears in list of WiFi networks
      PWC_HOTSPOT_PASSWORD: "balena01" # Optional. Must be 8 characters or more

      # Required system variables
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    network_mode: "host"
    restart: always
    volumes:
      - "pwc_db:/app/db" # Optional if not setting the hotspot ssid and password via the API
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    privileged: true # This can be removed if you do not need the LED connectivity indicator.

volumes:
  bdi_db:
  bdi_storage:
  pwc_db:
